### ISSUE TITLE
Set a limit for the size of translation tasks

### ISSUE THREAD

**Issue by hbarcelos** [kleros/linguo#14]
For the cryptoeconomic models created by @whwgeorge to work properly as the smart contract is implemented today, it's important that tasks can't vary too much in difficulty, so we will set a hard limit for the amount of words in a translation task.

**Comment by clesaege** [comment]
No need for that, if the number of words is higher, challenger will only look at a sample of the translation. This should still ensure economic incentives to make good translations.
