### ISSUE TITLE
Crash after creating task

### ISSUE THREAD

**Issue by mtsalenc** [kleros/linguo#21]
Steps that caused the issue:
1- I created a translation request from english to portuguese.
2- Navigated to "Work as a translator" (https://linguo-beta.netlify.app/translator?filter=inReview&secondLevelFilter=toReview)
3- Crash.

At this point opening a new tab and navigating to https://linguo-beta.netlify.app/translator?filter=inReview&secondLevelFilter=toReview crashes.

**Comment by mtsalenc** [comment]
Console:
```
Handling 'connect' event src.a9ec15a3.js:6532:2076
Handling 'chainChanged' event with payload 0x2a src.a9ec15a3.js:6532:2138
Handling 'networkChanged' event with payload 42 src.a9ec15a3.js:6532:2322
Handling 'accountsChanged' event with payload 
Array [ "0xdc8c1a8cb38f27c188a43ce0ebbc8e42e393d0d3" ]
src.a9ec15a3.js:6532:2225
MetaMask: The event 'data' is deprecated and may be removed in the future. inpage.js:1:15828
TypeError: e.secondLevelFilter is undefined
    setFilters src.a9ec15a3.js:6598
    B src.a9ec15a3.js:4194
    produce src.a9ec15a3.js:4188
    ...
```

**Comment by hbarcelos** [comment]
Looks like there's a problem with the state shape from a previous version.
I'm adding some additional checks to prevent the crash.
In the meantime, if you wipe your localstorage clean, the issue will go away
