### ISSUE TITLE
Evidence is not currently being submitted as "evidence.json"

### ISSUE THREAD

**Issue by greenlucid** [kleros/linguo#23]
[I submitted evidence before](https://etherscan.io/tx/0xd910bd05273ac8470ed43a2ce86365cd0039cb44eb2159d764daa5ffcfd754a0#eventlog) and the `_evidence` field of the Evidence event was `linguo-evidence-ikSDT7RQuo.json` instead of just `evidence.json`
All other Kleros dapps are currently using `evidence.json`, so for consistency + gas savings, the filename should just stay as `evidence.json`, unless there's a reason I haven't caught up yet.

**Comment by hbarcelos** [comment]
Thanks for reporting.
This was already fixed in a previous release.
