### ISSUE TITLE
Automatically prefill the number of words for common text formats

### ISSUE THREAD

**Issue by clesaege** [kleros/linguo#25]
![image](https://user-images.githubusercontent.com/8873352/101372813-329eec00-38a4-11eb-8ed0-5bffdf5d13de.png)
Automatically count the number of words in the document and prefill it (while still allowing it to be overwritten) for common formats (.txt, .md. json, etc).

**Comment by hbarcelos** [comment]
Fixed by linguo@fe14327d322d16b6e48a2c47ba007610f4b59537
