### ISSUE TITLE
Do not ask to sign up to 3D box unless it's required for a particular action

### ISSUE THREAD

**Issue by clesaege** [kleros/linguo#30]
![image](https://user-images.githubusercontent.com/8873352/102794223-f6d74c80-43a2-11eb-833e-74df105ccb09.png)

**Comment by hbarcelos** [comment]
I can move the 3box provider to the Task Details view, where comments are displayed.
It will still show that popup once the page is loaded, because the first step on 3box is to enable what they call the _space_, which requires consent of the user.
