### ISSUE TITLE
Do not show a pop under about word count

### ISSUE THREAD

**Issue by clesaege** [kleros/linguo#31]
It's annoying users and inspire distrust.

**Comment by hbarcelos** [comment]
As per discussion, let's change the Primary Document for new tasks:

> ## Regarding word count
> Since there is no reliable way of automatically determining the word count for all of the most common file formats, its input is ultimately under control of the translation requester.
> Translators are required to translate texts only **up to 10% beyond the declared word count**. What exceeds this limit can be left out of or simply copied _ipsis litteris_ on the delivered text.
