### ISSUE TITLE
notification mails not received

### ISSUE THREAD

**Issue by lalbinati** [kleros/linguo#36]
Whenever a translation gets approved and the payment is sent, although in the UI the notification is shown, the email notification is not sent.
I don't know if this problem is extensive to the other notifications.
I've checked this issue with another translator and he is experiencing the same issue.

**Comment by hbarcelos** [comment]
The e-mail notification service has been updated and will work for xDAI Chain only.
The release on xDAI Chain should happen within the next couple of weeks.
