### ISSUE TITLE
Payment with KPNK throws

### ISSUE THREAD

**Issue by mtsalenc** [kleros/linguo#6]
After unlocking permanently PNK, I am unable to request the payment:
![Screenshot from 2020-07-15 10-47-33](https://user-images.githubusercontent.com/9872474/87552893-a982e080-c688-11ea-8b19-1b860e1c56b3.png)
![Screenshot from 2020-07-15 10-48-34](https://user-images.githubusercontent.com/9872474/87552955-c3242800-c688-11ea-8065-a3b32349215b.png)

My address with KPNK: 0xdC8C1a8CB38F27C188a43CE0eBBC8e42e393D0d3

I went ahead and created it with ETH without problems: https://linguo-beta.netlify.app/translation/0x0825f16598AcB518851f8959b8267EF296c57f81/30

**Comment by hbarcelos** [comment]
Found the problem:
I swapped the selectors for Linguo and LinguoToken contracts, so it was returning the address for the wrong contract.

Will push the fix soon.
